---
application:
  name: "InstaXBot"
  project: "bot"
  organization: "Hellion Bots"
databases:
- type: "Mongo"
  name: "InstaX"
  version: "1"
routers:
- name: "master-instagram_manager_bot"
  routes:
  - application_name: "instagram_manager_bot"
    paths:
    - "/*"